# Generated by Django 5.1.6 on 2025-04-20 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafe',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
